# Generated by Django 5.0.6 on 2024-06-24 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('performers', models.TextField()),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('assigned', 'Назначена'), ('in_progress', 'Выполняется'), ('paused', 'Приостановлена'), ('completed', 'Завершена')], default='assigned', max_length=20)),
                ('planned_effort', models.DurationField()),
                ('actual_effort', models.DurationField()),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='api.task')),
            ],
        ),
    ]
