version: '3'
services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: ttdmd
    ports:
      - "5431:5432"
    networks:
      - mynetwork
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - database
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/frontend
    command: npm run serve
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge